// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package bookingDB

import (
	"context"
)

type Querier interface {
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
}

var _ Querier = (*Queries)(nil)
