// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package bookingDB

import (
	"context"
	"database/sql"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (ticket_id, status, user_id, event_category_id, event_id)
VALUES ($1, $2, $3, $4, $5)
    RETURNING id, ticket_id, status, created_at, user_id, event_id, event_category_id
`

type CreateBookingParams struct {
	TicketID        sql.NullInt32 `json:"ticket_id"`
	Status          string        `json:"status"`
	UserID          int32         `json:"user_id"`
	EventCategoryID int32         `json:"event_category_id"`
	EventID         int32         `json:"event_id"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.TicketID,
		arg.Status,
		arg.UserID,
		arg.EventCategoryID,
		arg.EventID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Status,
		&i.CreatedAt,
		&i.UserID,
		&i.EventID,
		&i.EventCategoryID,
	)
	return i, err
}
