// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ticketDB

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	ID        uuid.UUID `json:"id"`
	TicketID  int32     `json:"ticket_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type CategoryType struct {
	Name string `json:"name"`
}

type Event struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Location    string         `json:"location"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type EventCategory struct {
	ID             int32          `json:"id"`
	EventID        int32          `json:"event_id"`
	Name           string         `json:"name"`
	CategoryType   sql.NullString `json:"category_type"`
	Price          string         `json:"price"`
	BookType       string         `json:"book_type"`
	TotalCapacity  int32          `json:"total_capacity"`
	AvailableStock int32          `json:"available_stock"`
}

type EventImage struct {
	ID           int32         `json:"id"`
	EventID      int32         `json:"event_id"`
	ImageKey     string        `json:"image_key"`
	IsPrimary    sql.NullBool  `json:"is_primary"`
	DisplayOrder sql.NullInt32 `json:"display_order"`
	CreatedAt    sql.NullTime  `json:"created_at"`
}

type Ticket struct {
	ID              int32          `json:"id"`
	EventCategoryID int32          `json:"event_category_id"`
	SeatNumber      sql.NullString `json:"seat_number"`
	Status          sql.NullString `json:"status"`
	ReservedUntil   sql.NullTime   `json:"reserved_until"`
	Version         sql.NullInt32  `json:"version"`
}
