// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ticketDB

import (
	"context"
)

type Querier interface {
	InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	InsertEventCategory(ctx context.Context, arg InsertEventCategoryParams) (EventCategory, error)
	InsertEventImage(ctx context.Context, arg InsertEventImageParams) (EventImage, error)
	InsertTicket(ctx context.Context, arg InsertTicketParams) (Ticket, error)
}

var _ Querier = (*Queries)(nil)
