// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ticketDB

import (
	"context"
)

type Querier interface {
	BrowseEvents(ctx context.Context, arg BrowseEventsParams) ([]BrowseEventsRow, error)
	DeleteEventImage(ctx context.Context, imageKey string) error
	GetEventCategories(ctx context.Context, eventID int32) ([]EventCategory, error)
	GetEventDetails(ctx context.Context, id int32) (Event, error)
	GetEventImages(ctx context.Context, eventID int32) ([]EventImage, error)
	InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	InsertEventCategory(ctx context.Context, arg InsertEventCategoryParams) (EventCategory, error)
	InsertEventImage(ctx context.Context, arg InsertEventImageParams) (EventImage, error)
	InsertTicket(ctx context.Context, arg InsertTicketParams) (Ticket, error)
	UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
