// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ticketDB

import (
	"context"
)

type Querier interface {
	InsertEvents(ctx context.Context, arg InsertEventsParams) (Event, error)
	InsertEventsCategory(ctx context.Context, arg InsertEventsCategoryParams) (EventCategory, error)
	InsertTickets(ctx context.Context, arg InsertTicketsParams) (Ticket, error)
}

var _ Querier = (*Queries)(nil)
