// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package ticketDB

import (
	"context"
	"database/sql"
	"time"
)

const insertEvents = `-- name: InsertEvents :one
INSERT INTO events (name, description, location, start_time, end_time, created_at)
VALUES ($1,$2, $3, $4, $5, $6)
RETURNING id, name, description, location, start_time, end_time, created_at
`

type InsertEventsParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Location    string         `json:"location"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) InsertEvents(ctx context.Context, arg InsertEventsParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvents,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.CreatedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const insertEventsCategory = `-- name: InsertEventsCategory :one
INSERT INTO event_categories (
    id, event_id, category_type, price,
    book_type, total_capacity, available_stock
) VALUES (
 $1,$2, $3, $4, $5, $6, $7
)
RETURNING id, event_id, name, category_type, price, book_type, total_capacity, available_stock
`

type InsertEventsCategoryParams struct {
	ID             int32          `json:"id"`
	EventID        sql.NullInt32  `json:"event_id"`
	CategoryType   sql.NullString `json:"category_type"`
	Price          string         `json:"price"`
	BookType       string         `json:"book_type"`
	TotalCapacity  int32          `json:"total_capacity"`
	AvailableStock int32          `json:"available_stock"`
}

func (q *Queries) InsertEventsCategory(ctx context.Context, arg InsertEventsCategoryParams) (EventCategory, error) {
	row := q.db.QueryRowContext(ctx, insertEventsCategory,
		arg.ID,
		arg.EventID,
		arg.CategoryType,
		arg.Price,
		arg.BookType,
		arg.TotalCapacity,
		arg.AvailableStock,
	)
	var i EventCategory
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.CategoryType,
		&i.Price,
		&i.BookType,
		&i.TotalCapacity,
		&i.AvailableStock,
	)
	return i, err
}

const insertTickets = `-- name: InsertTickets :one
INSERT INTO tickets (event_category_id, seat_number, status, reserved_until, version)
VALUES ($1,$2, $3, $4, $5)
RETURNING id, event_category_id, seat_number, status, reserved_until, version
`

type InsertTicketsParams struct {
	EventCategoryID sql.NullInt32  `json:"event_category_id"`
	SeatNumber      sql.NullString `json:"seat_number"`
	Status          sql.NullString `json:"status"`
	ReservedUntil   sql.NullTime   `json:"reserved_until"`
	Version         sql.NullInt32  `json:"version"`
}

func (q *Queries) InsertTickets(ctx context.Context, arg InsertTicketsParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, insertTickets,
		arg.EventCategoryID,
		arg.SeatNumber,
		arg.Status,
		arg.ReservedUntil,
		arg.Version,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.EventCategoryID,
		&i.SeatNumber,
		&i.Status,
		&i.ReservedUntil,
		&i.Version,
	)
	return i, err
}
