// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package ticketDB

import (
	"context"
	"database/sql"
	"time"
)

const deleteEventImage = `-- name: DeleteEventImage :exec
DELETE FROM event_images
WHERE image_key = $1
`

func (q *Queries) DeleteEventImage(ctx context.Context, imageKey string) error {
	_, err := q.db.ExecContext(ctx, deleteEventImage, imageKey)
	return err
}

const insertBooking = `-- name: InsertBooking :one
INSERT INTO bookings (ticket_id, status)
VALUES ($1, $2)
    RETURNING id, ticket_id, status, created_at
`

type InsertBookingParams struct {
	TicketID int32  `json:"ticket_id"`
	Status   string `json:"status"`
}

func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, insertBooking, arg.TicketID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (name, description, location, start_time, end_time)
VALUES ($1, $2, $3, $4, $5)
    RETURNING id, name, description, location, start_time, end_time, created_at
`

type InsertEventParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Location    string         `json:"location"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, insertEvent,
		arg.Name,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const insertEventCategory = `-- name: InsertEventCategory :one
INSERT INTO event_categories (event_id, name, category_type, price, book_type, total_capacity, available_stock)
VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id, event_id, name, category_type, price, book_type, total_capacity, available_stock
`

type InsertEventCategoryParams struct {
	EventID        int32          `json:"event_id"`
	Name           string         `json:"name"`
	CategoryType   sql.NullString `json:"category_type"`
	Price          string         `json:"price"`
	BookType       string         `json:"book_type"`
	TotalCapacity  int32          `json:"total_capacity"`
	AvailableStock int32          `json:"available_stock"`
}

func (q *Queries) InsertEventCategory(ctx context.Context, arg InsertEventCategoryParams) (EventCategory, error) {
	row := q.db.QueryRowContext(ctx, insertEventCategory,
		arg.EventID,
		arg.Name,
		arg.CategoryType,
		arg.Price,
		arg.BookType,
		arg.TotalCapacity,
		arg.AvailableStock,
	)
	var i EventCategory
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.CategoryType,
		&i.Price,
		&i.BookType,
		&i.TotalCapacity,
		&i.AvailableStock,
	)
	return i, err
}

const insertEventImage = `-- name: InsertEventImage :one
INSERT INTO event_images (event_id, image_key, is_primary, display_order)
VALUES ($1, $2, $3, $4)
    RETURNING id, event_id, image_key, is_primary, display_order, created_at
`

type InsertEventImageParams struct {
	EventID      int32         `json:"event_id"`
	ImageKey     string        `json:"image_key"`
	IsPrimary    sql.NullBool  `json:"is_primary"`
	DisplayOrder sql.NullInt32 `json:"display_order"`
}

func (q *Queries) InsertEventImage(ctx context.Context, arg InsertEventImageParams) (EventImage, error) {
	row := q.db.QueryRowContext(ctx, insertEventImage,
		arg.EventID,
		arg.ImageKey,
		arg.IsPrimary,
		arg.DisplayOrder,
	)
	var i EventImage
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ImageKey,
		&i.IsPrimary,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const insertTicket = `-- name: InsertTicket :one
INSERT INTO tickets (event_category_id, seat_number, status, reserved_until)
VALUES ($1, $2, $3, $4)
    RETURNING id, event_category_id, seat_number, status, reserved_until, version
`

type InsertTicketParams struct {
	EventCategoryID int32          `json:"event_category_id"`
	SeatNumber      sql.NullString `json:"seat_number"`
	Status          sql.NullString `json:"status"`
	ReservedUntil   sql.NullTime   `json:"reserved_until"`
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, insertTicket,
		arg.EventCategoryID,
		arg.SeatNumber,
		arg.Status,
		arg.ReservedUntil,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.EventCategoryID,
		&i.SeatNumber,
		&i.Status,
		&i.ReservedUntil,
		&i.Version,
	)
	return i, err
}
